Create a 3×3 matrix with random float values between 0 and 1.

Compute and print the transpose of that matrix.

Multiply your original 3×3 matrix with its transpose using matrix multiplication.

Compute the determinant of a new 3×3 matrix.

Check if a matrix is invertible (i.e., has a non-zero determinant).

Calculate the inverse of an invertible 3×3 matrix.

Verify that a matrix multiplied by its inverse is (approximately) the identity matrix.

Set the random seed to 123 and generate 1,000 standard normal values.

Compute the mean and standard deviation of those values and compare them to the expected values for a standard normal distribution.

Generate a 2D array (shape 100×5) of standard normal values and calculate the column-wise means.

Generate 10,000 samples from a lognormal distribution with mean = 0.05 and sigma = 0.2.

Plot a histogram of the lognormal samples using 50 bins.

Use the Black-Scholes formula to simulate one stock price at maturity using: 
- S = 100, K = 105, r = 0.05, T = 1, theta = .2

Simulate 10,000 final stock prices using the formula: 
- St = So * exp((r - .5 * theta^2) * T + theta * sqrt(T) * Z) where Z ~ N(0,1)

Plot a histogram of the simulated prices and estimate the probability the stock ends up above the strike price (e.g., 105).

In [4]:
import numpy as np

rng = np.random.default_rng()
a = rng.random((3,3))
print(a)

[[0.69546545 0.69633653 0.45662763]
 [0.8510921  0.62608719 0.59387667]
 [0.04460427 0.74158034 0.98398028]]


In [5]:
b = a.T
print(b)

[[0.69546545 0.8510921  0.04460427]
 [0.69633653 0.62608719 0.74158034]
 [0.45662763 0.59387667 0.98398028]]


In [7]:
c = a @ b
print(c)

[[1.17706555 1.29905303 0.9967228 ]
 [1.29905303 1.46903243 1.08661923]
 [0.9967228  1.08661923 1.52014814]]


In [8]:
d = np.linalg.det(c)
print(d)

0.027921800068687278


In [12]:
if not np.isclose(d, 0):
    print(True)
else:
    print(False)

True


In [13]:
e = np.linalg.inv(c)
print(e)

[[ 37.69117908 -31.93543719  -1.88534076]
 [-31.93543719  28.5030936    0.56492432]
 [ -1.88534076   0.56492432   1.49018666]]


In [19]:
f = c @ e
print(f)

[[ 1.00000000e+00 -3.44169138e-15  2.22044605e-16]
 [-1.02140518e-14  1.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00 -3.55271368e-15  1.00000000e+00]]
