NumPy Quickstart 

The Basics 

Notes: 
- Dimensions are called axes 
- Array class is called ndarray 
- ndarray.ndim = number of axes of array 
- ndarray.shape = tuple of axes of n rows and m columns (n,m)
- ndarray.size = total number of elements in array (n x m)
- ndarray.dtype = object describing type of elements in array (int, numpy.int16)
- ndarray.itemsize = size in bytes of each element in array 
- ndarray.data = buffer containing actual elements of array 

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim 

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.itemsize

8

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

Array Creation 

Notes: 
- Can create an array from a regular python list or tuple using array function
    - i.e. a = np.array([2, 3, 4]); use brackets and parenthesis
- array transforms sequences of sequences into multidimensional array
    - i.e. b = np.array([1, 2, 3], [4, 5, 6])
    - b = [[1, 2, 3]
          [4, 5, 6]]
- type of array can be explicitly specified at creation time
    - i.e. c = np.array([1, 2, 3], dtype=complex)
- zeros creates an array filled with zeros
- ones creates an array filled with ones
- empty creates an array with content depending on state of memory
- arange function provides sequence of numbers analogous to python's range (accepts float arguments)
- linspace works better for floats with last number being number of elements versus the arange's step
    - i.e. np.linspace(0, 2, 9) gives off 9 numbers from 0 to 2

In [10]:
from numpy import pi
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
x = np.linspace(0, 2 * pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [12]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

Printing Arrays 

Notes:
- When you print an array, NumPy displays it in a similar way to nested lists
    - the last axis is printed from left to right
    - the second-to-last is printed from top to bottom
    - the rest are also printed from top to bottom, with each slice separated from the next by an empty line
- If an array is too large to be printed, NumPy automaticallly skips the central part and only prints the corners

In [13]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [14]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

print(b)

In [15]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


Basic Operations 

Notes: 
- Arithmetic operators on arrays apply elementwise, new array is created and filled with result

In [17]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
print(c)

[20 29 38 47]


- The product operator (*) operates elementwise in NumPy.
- The matrix product operator can either be used with @ or the dot function.

In [18]:
a = np.array([[1, 1],[0,1]])
b = np.array([[2, 0], [3,4]])
print(a @ b)
print(a.dot(b))

[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


- Some operations, such as += and *=, act in place to modify an exisiting array rather than to create a new one.

In [19]:
a = np.array([1, 2, 3])
a *= 3
print(a)

[3 6 9]


In [20]:
a += 7
print(a)

[10 13 16]


- When operating with arrays of different types, the type of the resulting array will be the more general or more precise one (this behavior is called upcasting). 

In [21]:
a = np.arange(3)
b = np.linspace(0, pi, 3)
print(a)
print(b)
c = a + b
print(c)

[0 1 2]
[0.         1.57079633 3.14159265]
[0.         2.57079633 5.14159265]


- Many unary operators, such as computing the sum of all elements in the array are implemented as methods of the ndarray class.

In [22]:
a = np.arange(10)
print(a)
print(a.sum())
print(a.max())
print(a.min())

[0 1 2 3 4 5 6 7 8 9]
45
9
0


- Can apply these same operations to a specific axis

In [23]:
a = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(a.sum(axis=0))
print(a.min(axis=1))
print(a.cumsum(axis=1))

[ 60  80 100 120]
[10 50]
[[ 10  30  60 100]
 [ 50 110 180 260]]


Universal Functions

Notes: 
- NumPy provides familiar mathematical functions like sin, cos, exp.
- These are called universal functions or ufunc.
- Functions operate elementwise on an array, producing an array as output. 

In [24]:
b = np.arange(5)
print(np.exp(b))
print(np.sin(b))
print(np.cos(b))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


Indexing, Slicing, and Iterating 

Notes:
- 1-D arrays can be indexed, sliced, and iterated over like lists in Python
- Multidimensional arrays can have one index per axis; given in a tuple seperated by commas
- Can use the dots (...), to fill in multiple axis indices
    - i.e. 5-D array, and you write x[0, ...], this fills in the rest of the indices needed
- Iterating over multidimensional arrays is done with respect to the first axis (rows)
- When wanting to perform an operation to each element in the array (not all arrays in multidimensional array are the same length), you use the flat function (x.flat)

In [25]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
a[:6:2] = 1000
print(a)

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]


In [26]:
b = np.arange(24).reshape(3,8)
print(b)
print(b[2,3])
print(b[1:3, 2])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
19
[10 18]


In [27]:
for row in b: 
    print(row)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


In [28]:
for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


Shape Manipulation 

Changing the Shape of an Array 

Notes: 
- The shape of an array can be changed with various commands, all return a modified array but don't change the original array
- .ravel() returns a flattened array
- .reshape() changes to given shape
- .T() returns transposed array
- ndarray.resize modifies array itself (changes original array)
- If a dimension is given a -1, then the reshaping is automatically calculated

In [29]:
a = np.arange(36).reshape(6,6)
print(a)
print(a.ravel())
print(a.reshape(3,12))
print(a.T)
print(a.reshape(2, -1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
[[ 0  6 12 18 24 30]
 [ 1  7 13 19 25 31]
 [ 2  8 14 20 26 32]
 [ 3  9 15 21 27 33]
 [ 4 10 16 22 28 34]
 [ 5 11 17 23 29 35]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]


Stacking Together Different Arrays 

Notes: 
- Several arrays can be stacked together along different axes using hstack or vstack
- The function column_stack stacks 1-D arrays as columns into a 2D array (equivalent to hstack only for 2D arrays)
- newaxis (has to be imported) is a constant equal to none in order to be able to insert an index when needed
- In general for arrys with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for optional arguments giving the number of the axis along which the concatenation should happen
- r__ and c__ allow for stacking of different array with different ranges 

In [33]:
a = np.arange(4).reshape(2,2)
b = np.arange(4).reshape(2,2)
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.column_stack((a,b)))

[[0 1]
 [2 3]
 [0 1]
 [2 3]]
[[0 1 0 1]
 [2 3 2 3]]
[[0 1 0 1]
 [2 3 2 3]]
