Create a 1D NumPy array containing integers from 0 to 19.

Create a 4×5 2D array filled with zeros, then set all elements in the second row to 1.

Create a 3×3 identity matrix using a NumPy built-in function.

Generate a 1D array of 50 values between 0 and 10 (inclusive) using linspace.

Create a 5×5 matrix with random integers between 10 and 99.

From a 1D array of numbers 0 to 29, reshape it into a 6×5 matrix, then extract the last two rows.

Slice out the second column of a 4×4 matrix.

Take a 3×3 matrix and flatten it into a 1D array.

From a 5×5 matrix, replace all elements divisible by 3 with -1.

Create two 2×3 arrays with random values and add them together elementwise.

Take an array of numbers from 0 to 9 and square each element using vectorized syntax.

Create a 5×5 array of random floats and clip all values to stay between 0.2 and 0.8.

Create a 100-element array of random values and compute the mean, std, min, and max.

Generate a 6×6 matrix of integers and compute the sum of each column and each row.

Create a column vector of shape (5,1) and a row vector of shape (1,4), then use broadcasting to produce a 5×4 matrix where each entry is their product.

In [1]:
import numpy as np

a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
b = np.zeros((4,5))
print(b)
b[1,:] = 1
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
d = np.linspace(0, 10, 50)
print(d)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [5]:
rng = np.random.default_rng()
e = rng.integers(10, 100, size=(5,5))
print(e)

[[51 59 47 56 81]
 [45 44 50 28 21]
 [47 66 17 10 12]
 [86 93 63 20 22]
 [80 14 58 76 73]]


In [6]:
f = np.arange(30)
print(f)
g = f.reshape(6,5)
print(g[0:4])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
h = np.arange(16).reshape(4,4)
print(h)
i = h[:, 1]
print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  5  9 13]


In [8]:
j = np.arange(9).reshape(3,3)
print(j)
k = j.ravel()
print(k)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [9]:
l = np.arange(25).reshape(5,5)
mask = l % 3 == 0
l[mask] = -1
print(l)

[[-1  1  2 -1  4]
 [ 5 -1  7  8 -1]
 [10 11 -1 13 14]
 [-1 16 17 -1 19]
 [20 -1 22 23 -1]]


In [10]:
rng = np.random.default_rng()
m = rng.integers(99, size=(2,3))
print(m)
n = rng.integers(99, size=(2,3))
print(n)
print(m + n)

[[57 78 66]
 [75 78 76]]
[[85 89 47]
 [23 21 53]]
[[142 167 113]
 [ 98  99 129]]


In [11]:
o = np.arange(10)
print(o)
p = o ** 2
print(p)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [12]:
rng = np.random.default_rng()
q = rng.random((5,5))
q_clip = np.clip(q, .2, .8)
print(q_clip)

[[0.2901787  0.47095131 0.53093351 0.8        0.2       ]
 [0.8        0.2839379  0.8        0.65890997 0.36345562]
 [0.32064168 0.76520664 0.7352853  0.8        0.22954005]
 [0.52899995 0.2        0.8        0.8        0.40543812]
 [0.20494941 0.2        0.8        0.2        0.2       ]]


In [13]:
r = rng.integers(0, 100, size=(10,10))
print(r)
print(r.mean())
print(r.std())
print(r.max())
print(r.min())

[[ 6  7 14 68 46 88 96 68 18 30]
 [ 2 63  5 25 14  6 94  6 92  5]
 [66 23 71 56 23 39 92 71 15 70]
 [74 21  3 62 18 93 21  7 35 96]
 [33 79 29 48 25 47 56 34 92 46]
 [63 68  1 70 24  9 59 50 27 49]
 [41 81 46 28 20 74 37 24 65 13]
 [38 77 70 98 47 64 76  4 35 92]
 [29 22 76 60 37 88 80 17 68 64]
 [62 18 99  1 51 16 44 21 34 96]]
46.31
29.027812525231724
99
1


In [14]:
s = np.arange(36).reshape(6,6)
print(s)
print(s.sum(axis=0))
print(s.sum(axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 90  96 102 108 114 120]
[ 15  51  87 123 159 195]


In [15]:
t = np.arange(1, 6).reshape(5,1)
print(t)
u = np.arange(1, 5).reshape(1,4)
print(u)
result = t * u
print(result)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]
