NumPy Glossary 

ndarray: numpy's array class; also known as array 
- np.array() is how to initiliaze an object to the ndarray class
- ndarray is not a function 

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


np.array(): initiliaztion of array
- takes a specific array and dtype as parameters
- have to use ( and [; array([1, 2, 3])
- dtype can be specified at creation time 

In [2]:
a = np.array([2, 4, 6], dtype=np.float64)
print(a)

[2. 4. 6.]


np.zeros(): initializes an array filled with zeros
- takes the shape of an array as parameter
- does not modify a list, only creates a new one

In [3]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.ones(): initializes an array filled with ones
- takes an array shape as parameter
- does not modify a list, only creates new one

In [4]:
a = np.ones((2, 2))
print(a)

[[1. 1.]
 [1. 1.]]


np.empty(): initializes an array filled with random values from memory 
- takes array shape as parameter
- completely random float64 values, dtype can be changed

In [5]:
a = np.empty((4,4))
print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.60218491e-306]
 [8.34441742e-308 1.78022342e-306 6.23058028e-307 9.79107872e-307]
 [6.89807188e-307 7.56594375e-307 6.23060065e-307 1.78021527e-306]
 [8.34454050e-308 1.11261027e-306 1.15706896e-306 1.33512173e-306]]


np.arange(): same as the range function in python
- takes, start, stop, step, dtype as parameters
- arange(stop); one parameter
- arange(start, stop) two parameters
- creates a new array 

In [6]:
a = np.arange(0, 101, 10) 
print(a)

[  0  10  20  30  40  50  60  70  80  90 100]


np.linspace(): works similar to arange but specificaly with floats 
- takes start, stop, num, endpoint, retstep
- returns an array with num values between the start and stop (inclusive)
- if endpoint is false, stop is not included in interval
- retstep prints out the step used in interval
- all elements are evenly spaced 

In [7]:
a = np.linspace(0, 10, 10, endpoint=False, retstep=True)
print(a)

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), np.float64(1.0))


np.reshape(): modifies an array to be reshaped with specific axes
- takes array and/or new shape as parameters
- can be used alongside arange in order to shape a newly created array
- can also be used on an exisiting array in order to reshape it
- can take a '-1' as parameter for an axis that is unknown/unspecified 

In [8]:
a = np.arange(0, 100, 10).reshape(5, -1)
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)
np.reshape(b, (5, 2))
print(b)

[[ 0 10]
 [20 30]
 [40 50]
 [60 70]
 [80 90]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


.dot(): applies matrix product 
- called on an array and takes an array as a parameter
- also can be denoted as @, arrayA @ arrayB

In [9]:
a = np.arange(16).reshape(4,4)
b = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
print(a.dot(b))

[[  6  12  18  24]
 [ 22  44  66  88]
 [ 38  76 114 152]
 [ 54 108 162 216]]


numpy.random: legacy module in NumPy that provides tools for generating random numbers
- not a function that you call or use
- allows to use other random functions 

np.random.default_rng(): creates instance of default random number generator; modern 
- takes seed as parameter (optional)
- usually saved as a variable 

np.rng.random(): creates an array filled with random numbers based on generator
- takes size as a parameter
- default floats between 0 and 1

np.rng.integers(): creates an array filled with random integers 
- takes low, high, size, endpoint as parameters

np.rng.standard_normal(): draws samples from a standard normal distribution, (mean=0, stdev=1)
- takes size as parameter (how many samples)

In [10]:
rng = np.random.default_rng(2)
a = rng.random((2, 2))
b = rng.integers(1, 100, (5,5), endpoint=True)
print(a)
print(b)

c = rng.standard_normal(10)
print(c)

[[0.26161213 0.29849114]
 [0.81422574 0.09191594]]
[[ 34  61  82  73 100]
 [ 19  89   6  56  28]
 [ 21  66  31  57  27]
 [ 16  75  44  68  67]
 [ 95  43  22  64  94]]
[-0.6071857   0.12682785 -0.89227404  0.84146497  0.18803509  0.33057101
  0.41050391 -1.0107575   0.783181    2.05670282]


.ravel(): returns a falttened array (1-D)
- called on an array
- does not change the original list 

In [11]:
a = np.arange(16).reshape(4,4)
print(a)
print(a.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


.T: returns a tranposal of an array 
- not a function but a method in ndarray class 
- called on an array
- does not change the original list 

In [12]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(a)
b = a.T
print(b)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


.resize(): method modifies the array itself versus returning a modified shape
- called on an array 

In [13]:
a = np.arange(16).reshape(4,4)
print(a)
a.resize(2, 8)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


np.vstack(): vertically stacks multiple arrays 
- takes arrays as parameters
- creates new array
- all arrays must have the same number of columns 

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c = np.vstack((a, b))
print(c)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


np.hstack(): horizontally stacks multiple arrays 
- takes arrays as parameters
- creates new array
- all arrays must have the same number of rows 

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c = np.hstack((a, b))
print(c)

[[1 2 3 1 2 3 4]
 [4 5 6 5 6 7 8]]


np.column_stack(): takes 1-D arrays and stacks them into columns in a 2-D array 
- takes arrays as parameters
- works best with 1-D to 2-D
- all arrays must have the same amount of elements; number of rows 

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b,))
d = np.column_stack((a, b))
print(c)
print(d)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


np.concatenate(): more general way of combining arrays, using specified axis 
- takes arrays and axis as parameter

In [17]:
a = np.arange(16).reshape(2, 8)
b = np.arange(24).reshape(2,12)
c = np.concatenate((a, b), axis=1)
print(c)

[[ 0  1  2  3  4  5  6  7  0  1  2  3  4  5  6  7  8  9 10 11]
 [ 8  9 10 11 12 13 14 15 12 13 14 15 16 17 18 19 20 21 22 23]]


np.r_[]: a shorthand syntax way of stacking and creating arrays horizontally 
- takes arrays, indices and slicing as parameters
- combines all
- sugar syntax

In [18]:
a = np.r_[0:4, 7, 9, 11:19, [24, 25, 26]]
print(a)

[ 0  1  2  3  7  9 11 12 13 14 15 16 17 18 24 25 26]


np.c_[]: a shorthand syntax way of combining arrays and elements vertically
- takes arrays, indices, slicing as parameters
- combines all
- sugar syntax 

In [19]:
a = np.c_[[1, 2, 3], 4:7, [[9, 10, 11], [12, 16, 20], [24, 25, 26]]]
print(a)

[[ 1  4  9 10 11]
 [ 2  5 12 16 20]
 [ 3  6 24 25 26]]


np.hsplit(): splits an array along its horizontal axis
- takes array and number of indices (slices) as parameters
- indices can be specific; kind of like slicing
- requires an even split between pieces (equal amount of rows) 

In [20]:
a = np.arange(16).reshape(4,4)
print(a)
b = np.hsplit(a, [1, 3])
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


np.vsplit(): splits an array along its vertical axis 
- takes array and numbers of indices (slices) as parameters
- indices can be specific; kind of slicing
- requires an even split between pieces (equal amount of columns) 

In [21]:
a = np.arange(25).reshape(5, 5)
print(a)
b = np.vsplit(a, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24]])]


np.array_split(): splits arrays in specified axis 
- takes array, number of slices and axis as parameters
- does not need to split into equal parts 
- more flexible than hsplit and vsplit

In [22]:
a = np.arange(24).reshape(6, 4)
b = np.array_split(a, 4, axis=0)
print(b)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]


.view(): creates a new array object that looks at the same data 
- takes dtype as parameter
- kind of like a pointer
- b = a.view(); b is a new array object; but b and a share the same underlying data
- changing the contents of one affects the other
- changing the shape/structure of one does not affect the other  

In [23]:
a = np.arange(4)
c = a.view()
print(a)
print(c is a)
c[0] = 99
print(a)

[0 1 2 3]
False
[99  1  2  3]


.copy(): makes a complete copy of the array and its data 
- new array object with new data is created
- arrays will not be affected by each other 

In [24]:
a = np.arange(6)
b = a.copy()
b[0] = 100
print(a)
print(b)

[0 1 2 3 4 5]
[100   1   2   3   4   5]
