Basic Routines

Finding the Inverse: 
- The inverse of a matrix A is the matrix B, such that AB = I, where I is the identitiy matrix consisting of ones down the main diagonal. Usually, B is denoted B = A^-1.
- In SciPy, the matrix inverse of the NumPy array, A, is obtained using linalg.inv(A) or A.I if A is a matrix.

In [1]:
import numpy as np
from scipy import linalg 

A = np.array([[4, 7, 5], [6, 2, 1], [9, 2, 6]])
Inv = linalg.inv(A)
print(Inv)

[[-0.05586592  0.17877095  0.01675978]
 [ 0.15083799  0.11731844 -0.1452514 ]
 [ 0.03351955 -0.30726257  0.18994413]]


In [2]:
Ident = A.dot(linalg.inv(A))
print(Ident)

[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 4.16333634e-17  1.00000000e+00 -5.55111512e-17]
 [ 2.77555756e-17  2.22044605e-16  1.00000000e+00]]


Remember that a matrix can only have an inverse if it's determinant is not zero. When creating array examples,
use random numbers for the arrays because in arrays like; [[1, 2, 3], [4, 5, 6], [7, 8, 9]], rows depend on each other and this creates what's called a singular matrix and therefore does not have an inverse. Sometimes an error will pop up but not all the time. 

Solving a Linear System: 

- Linear System: a collection of linear equations, where the number of equations matches the number of variables. allowing for an algebraic solution
- ex: y = 3x + 1, y = -2x + 7; two equations, two variables (x, y)
- solve these using linalg.solve()
- expects an input matrix and a right-hand side vector; solution vector is then computed

In [3]:
# Equation 1: 2x + 3y = 8
# Equation 2: 4x - y = 2
A = np.array([[2, 3], [4, -1]])
B = np.array([8, 2])
solution = linalg.solve(A, B)
print(solution)

[1. 2.]


2(1) + 3(2) = 8 # Correct

4(1) - (2) = 2  # Correct 

Notes on Linear Systems: 
- The matrix A must be square
- A must be non-singular (i.e., invertible)
- The vector b should have the same number of rows as A

Finding the Determinant: 

